### ISSUE TITLE
Parameter button does cause editor to ask for value

### ISSUE THREAD

**Issue by vanlehn** [Dragoon-Lab/topomath#119] opened 2017-04-27 16:24 UTC
After filling out all the fields of a new quantity node, I click th eparameter button, and nothing happens.  It shoudl open fields for value and units.  when I close the node and reopen it, the menu has reset to be unknown.

**Comment by sachingrover211** [comment] 2017-04-28 00:35
The issue is fixed and code has been committed for this.

**Closed** 2017-05-01 22:07 UTC
